import { useMemo } from 'react'
import { generateTree, terminals } from './BronchialTree.js'

// Lung illustration driven by the simulation.
//
// The lungs are translucent so the airway tree inside them is visible, and
// that tree is generated by recursive bifurcation rather than drawn as a few
// fixed strokes — a parent dividing into two smaller daughters, repeating
// until the branches are too fine to draw. Anatomy is kept honest: three
// lobes on the right, two on the left with the cardiac notch, and a right
// main bronchus wider and more vertical than the left.
//
// Motion comes from the model. The lungs expand with delivered volume, the
// diaphragm descends as they fill, a stiffer lung visibly moves less, and the
// terminal units brighten on inspiration as gas reaches them.

const VIEWBOX = { w: 280, h: 320 }
const NOMINAL_VT = 500
const MAX_SCALE = 0.11

function lerp(a, b, x) {
  return a + (b - a) * Math.min(Math.max(x, 0), 1)
}

// Saturation drives the tint of the tissue: oxygenated pink toward a dusky
// blue-grey. A display choice, not a clinical threshold.
function tintFor(spo2) {
  const x = spo2 == null ? 0.75 : Math.min(Math.max((spo2 - 80) / 18, 0), 1)
  return {
    tissue: `rgb(${Math.round(lerp(96, 208, x))}, ${Math.round(lerp(108, 138, x))}, ${Math.round(lerp(150, 156, x))})`,
    edge: `rgb(${Math.round(lerp(132, 240, x))}, ${Math.round(lerp(150, 168, x))}, ${Math.round(lerp(190, 186, x))})`,
    airway: `rgb(${Math.round(lerp(150, 236, x))}, ${Math.round(lerp(120, 128, x))}, ${Math.round(lerp(140, 136, x))})`,
  }
}

const RIGHT_LUNG = `M 116 92
  C 88 100, 60 130, 53 172
  C 46 214, 57 252, 76 268
  C 93 281, 113 274, 118 252
  C 123 224, 122 148, 120 114 Z`

// The left lung carries the cardiac notch: the concavity where the heart sits.
const LEFT_LUNG = `M 164 92
  C 192 100, 220 130, 227 172
  C 234 214, 223 252, 204 268
  C 187 281, 167 274, 162 252
  C 159 232, 160 214, 169 203
  C 178 192, 178 181, 167 172
  C 158 164, 160 130, 164 114 Z`

export default function LungIllustration({
  volume = 0, tidalVolume = NOMINAL_VT, spo2 = null, compliance = 50, phase,
}) {
  const fill = Math.min(Math.max(volume / Math.max(tidalVolume, 1), 0), 1.15)
  const tint = useMemo(() => tintFor(spo2), [spo2])
  const inspiring = phase != null && String(phase).startsWith('inspiration')

  // A stiffer lung expands less for the same delivered volume.
  const complianceFactor = Math.min(Math.max(compliance / 50, 0.45), 1.15)
  const scale = 1 + fill * MAX_SCALE * complianceFactor
  const diaphragmDrop = fill * 11 * complianceFactor

  // One tree per lobe, springing from the hilum: three on the right and two
  // on the left, matching the lobar bronchi. Generating per lobe rather than
  // one tree per lung both fills the lower lobes and keeps the anatomy right.
  // Seeds are fixed so the trees are stable across renders.
  const rightTree = useMemo(() => [
    ...generateTree({ x: 124, y: 110, angle: 2.75, length: 17, width: 3.6, depth: 6, seed: 7, spread: 0.44 }),
    ...generateTree({ x: 124, y: 118, angle: 2.28, length: 19, width: 3.4, depth: 6, seed: 13, spread: 0.42 }),
    ...generateTree({ x: 122, y: 126, angle: 1.78, length: 22, width: 3.8, depth: 6, seed: 29, spread: 0.40 }),
  ], [])
  const leftTree = useMemo(() => [
    ...generateTree({ x: 156, y: 110, angle: 0.40, length: 18, width: 3.5, depth: 6, seed: 21, spread: 0.44 }),
    ...generateTree({ x: 158, y: 124, angle: 1.30, length: 22, width: 3.7, depth: 6, seed: 37, spread: 0.40 }),
  ], [])
  const rightTips = useMemo(() => terminals(rightTree), [rightTree])
  const leftTips = useMemo(() => terminals(leftTree), [leftTree])

  const renderTree = (branches, clipId) => (
    <g clipPath={`url(#${clipId})`}>
      {branches.map((b, i) => (
        <path
          key={i}
          d={b.d}
          fill="none"
          stroke={tint.airway}
          strokeWidth={Math.max(b.width, 0.5)}
          strokeLinecap="round"
          opacity={0.32 + (b.level / 6) * 0.58}
        />
      ))}
    </g>
  )

  return (
    <div className="lung-illustration">
      <svg
        viewBox={`0 0 ${VIEWBOX.w} ${VIEWBOX.h}`}
        role="img"
        aria-label={`Simulated lung, ${Math.round(volume)} millilitres above baseline`}
      >
        <defs>
          <clipPath id="clipRight"><path d={RIGHT_LUNG} /></clipPath>
          <clipPath id="clipLeft"><path d={LEFT_LUNG} /></clipPath>

          <linearGradient id="pleura" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={tint.edge} stopOpacity="0.30" />
            <stop offset="55%" stopColor={tint.tissue} stopOpacity="0.20" />
            <stop offset="100%" stopColor={tint.tissue} stopOpacity="0.34" />
          </linearGradient>
          <linearGradient id="cartilage" x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stopColor="#8e99a8" />
            <stop offset="45%" stopColor="#e2e8f0" />
            <stop offset="100%" stopColor="#8e99a8" />
          </linearGradient>
          <filter id="softGlow" x="-40%" y="-40%" width="180%" height="180%">
            <feGaussianBlur stdDeviation="4" result="b" />
            <feMerge><feMergeNode in="b" /><feMergeNode in="SourceGraphic" /></feMerge>
          </filter>
        </defs>

        {/* Ribs behind, giving the lungs a thorax to sit in */}
        <g opacity="0.13" stroke="currentColor" fill="none" strokeWidth="2.2" strokeLinecap="round">
          {[0, 1, 2, 3, 4, 5].map((i) => (
            <path key={i} d={`M 40 ${94 + i * 27} Q 140 ${70 + i * 27} 240 ${94 + i * 27}`} />
          ))}
        </g>

        <g
          style={{
            transformOrigin: '140px 130px',
            transform: `scale(${scale.toFixed(4)})`,
            transition: 'transform 90ms linear',
          }}
        >
          {/* Pleural envelopes, translucent so the airway shows through */}
          <path d={RIGHT_LUNG} fill="url(#pleura)" stroke={tint.edge} strokeWidth="1.5" strokeOpacity="0.8" />
          <path d={LEFT_LUNG} fill="url(#pleura)" stroke={tint.edge} strokeWidth="1.5" strokeOpacity="0.8" />

          {/* Fissures: two on the right for three lobes, one on the left */}
          <g stroke={tint.edge} strokeWidth="1.1" fill="none" opacity="0.55">
            <path d="M 57 152 C 80 146, 104 144, 119 147" />
            <path d="M 55 204 C 80 198, 104 196, 118 198" />
            <path d="M 224 166 C 200 159, 178 157, 163 160" />
          </g>

          {renderTree(rightTree, 'clipRight')}
          {renderTree(leftTree, 'clipLeft')}

          {/* Terminal units brighten as gas reaches them on inspiration.
              Clipped to their own lung so no glow falls outside the tissue. */}
          {[['clipRight', rightTips], ['clipLeft', leftTips]].map(([clipId, pts]) => (
            <g key={clipId} clipPath={`url(#${clipId})`} filter="url(#softGlow)">
              {pts.map((pt, i) => (
                <circle
                  key={i}
                  cx={pt.x}
                  cy={pt.y}
                  r={inspiring ? 1.4 + fill * 1.1 : 0.9}
                  fill={tint.edge}
                  opacity={inspiring ? 0.25 + fill * 0.45 : 0.15}
                />
              ))}
            </g>
          ))}

          {/* Trachea and carina, drawn over the lungs as they lie in front */}
          <g>
            <path d="M 132 22 L 148 22 L 148 96 L 132 96 Z" fill="url(#cartilage)" opacity="0.9" />
            {[0, 1, 2, 3, 4, 5, 6].map((i) => (
              <rect key={i} x="131" y={27 + i * 10} width="18" height="3.6" rx="1.8"
                fill="#0d1219" opacity="0.28" />
            ))}
            {/* The right main bronchus is wider and more vertical than the
                left, which is why aspirated material tends to enter it. */}
            <path d="M 138 92 Q 126 100 118 112 L 127 118 Q 135 104 144 98 Z" fill="url(#cartilage)" opacity="0.85" />
            <path d="M 144 92 Q 158 99 166 109 L 158 116 Q 149 103 140 98 Z" fill="url(#cartilage)" opacity="0.85" />
          </g>
        </g>

        {/* Diaphragm descends as the lungs fill */}
        <path
          d={`M 44 ${282 + diaphragmDrop} Q 140 ${312 + diaphragmDrop * 1.6} 236 ${282 + diaphragmDrop}`}
          fill="none"
          stroke="currentColor"
          strokeWidth="3"
          strokeLinecap="round"
          opacity="0.26"
          style={{ transition: 'd 90ms linear' }}
        />
      </svg>

      <div className="lung-readout">
        <span className="lung-volume tnum">{Math.round(volume)}</span>
        <span className="lung-volume-unit">mL above baseline</span>
      </div>
    </div>
  )
}
